spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-smoke-a1pljrz5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_lTd9CtBje3cP
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/key.pem
